{% set name = "miniopy-async" %}
{% set version = "1.21.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1b28bca3a80d7ae671206b560e7d5aaead581c1ffd0957d646056dec79f8318e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }}
    - certifi >= 2025.1.31
    - aiofile >= 3.9.0
    - aiohttp >= 3.11.14
    - urllib3 >= 2.3.0
    - typing-extensions >= 4.13.0

test:
  imports:
    - miniopy_async
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hlf20010508/miniopy-async
  summary: Asynchronous MinIO Client SDK for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hlf20010508
